name: ollama-gateway-quicktest
description: Quick testing configuration files on Docker
services:
  mock-ollama:
    image: mockserver/mockserver:latest
    container_name: ollama-gateway-mock-ollama
    ports:
      - "1080:11434"
    networks:
      - ollama-net

  nginx:
    image: nginx:1.31.3-alpine3.24
    container_name: ollama-gateway-nginx
    ports:
      - "8000:8000"
      - "8080:8080"
      - "80:80"
    volumes:
      - ./nginx/ollama.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - ollama-net

networks:
  ollama-net:
    driver: bridge
