# Default: /opt/homebrew/etc/nginx/nginx.conf
# Custom: /opt/homebrew/etc/nginx/servers/

upstream ollama {
    server localhost:11434;
}

server {
    listen 8080 default_server;
    server_name _;

    location /hello {
        add_header Content-Type text/plain; 
        return 200 "Hello World\n"; 
    }

    location /o/ {
        proxy_pass http://ollama/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 120s;
        proxy_connect_timeout 10s;
        proxy_http_version 1.1;
    }
}



